/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Hotel;
import Entidades.Negocios;
import Entidades.Reserva;
import Entidades.Vacaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaAltaReservas extends javax.swing.JFrame {
    private Hotel gestor;
    /**
     * Creates new form AltaReservas
     */
    public VentanaAltaReservas(Hotel gestor) {
        initComponents();
        this.gestor = gestor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chkVigente = new javax.swing.JCheckBox();
        txtNumHabit = new javax.swing.JTextField();
        txtDiasReserv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbVacaciones = new javax.swing.JRadioButton();
        rbNegocios = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtCantNinios = new javax.swing.JTextField();
        chkConferencia = new javax.swing.JCheckBox();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Alta de Reservas");

        jLabel2.setText("N° de Habitación");

        jLabel3.setText("Días Reservado");

        chkVigente.setText("Vigente");

        jLabel5.setText("Tipo de reserva");

        buttonGroup1.add(rbVacaciones);
        rbVacaciones.setSelected(true);
        rbVacaciones.setText("Vacaciones");
        rbVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVacacionesActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNegocios);
        rbNegocios.setText("Negocios");
        rbNegocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNegociosActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad de niños");

        chkConferencia.setText("Conferencia");
        chkConferencia.setEnabled(false);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumHabit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiasReserv, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbVacaciones)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantNinios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkConferencia)
                            .addComponent(rbNegocios)
                            .addComponent(btnAgregar))))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(chkVigente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumHabit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiasReserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkVigente)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbVacaciones)
                    .addComponent(rbNegocios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCantNinios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkConferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int numHabit = 0;
        int diasReservados = 0;
        boolean vigente;
        
        try{
            numHabit = Integer.parseInt(txtNumHabit.getText());
        }
        catch(Exception e){
            if(txtNumHabit.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Debe ingresar un nuúmero de habitación");
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Debe ingresar digitos numéricos");
                
            }
            return;
        }
        try{
            diasReservados = Integer.parseInt(txtDiasReserv.getText());
            
        }
        catch(Exception e){
            if(txtDiasReserv.getText().isEmpty())
                JOptionPane.showMessageDialog(null, "Debe ingresar la cantidad de días reservados");
            else
                JOptionPane.showMessageDialog(null, "Debe ingresar digitos numéricos");
            return;
        }
        
        vigente = chkVigente.isSelected();
        
        Reserva r = null;
        int cantNinios = 0;
        
        if(rbVacaciones.isSelected()){
            try{
                cantNinios = Integer.parseInt(txtCantNinios.getText());
                
            }
            catch(Exception e){
                if(txtCantNinios.getText().isEmpty())
                    JOptionPane.showMessageDialog(null, "Debe indicar la cantidad de ninios");
                else
                    JOptionPane.showMessageDialog(null, "Debe ingresar digitos numéricos");
                return;
            }
            
                
            r = new Vacaciones(cantNinios,numHabit,diasReservados,vigente);
        }
        else{
            boolean conferencia = chkConferencia.isSelected();
            r = new Negocios(conferencia,numHabit,diasReservados,vigente);
        }
        
        gestor.agregarReserva(r);
        
        JOptionPane.showMessageDialog(null, "Reserva ingresada correctamente");
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void rbVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVacacionesActionPerformed
        txtCantNinios.setEnabled(true);
        chkConferencia.setEnabled(false);
    }//GEN-LAST:event_rbVacacionesActionPerformed

    private void rbNegociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNegociosActionPerformed
        txtCantNinios.setEnabled(false);
        chkConferencia.setEnabled(true);
    }//GEN-LAST:event_rbNegociosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkConferencia;
    private javax.swing.JCheckBox chkVigente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbNegocios;
    private javax.swing.JRadioButton rbVacaciones;
    private javax.swing.JTextField txtCantNinios;
    private javax.swing.JTextField txtDiasReserv;
    private javax.swing.JTextField txtNumHabit;
    // End of variables declaration//GEN-END:variables
}
